### ISSUE TITLE
Update to Bootstrap v5

### ISSUE THREAD

**Issue by coderbyheart** [NordicSemiconductor/asset-tracker-cloud-app-js#277]
https://getbootstrap.com/docs/5.0/migration/
https://github.com/reactstrap/reactstrap/issues/1748
https://github.com/NordicSemiconductor/asset-tracker-cloud-app-js/pull/428

**Comment by a6you** [comment]
Hello, I'm Austin! I saw this issue on goodfirstissues.com and I thought it might be interesting to tackle. I don't have much experience with migrating Bootstrap versions, much less on a TypeScript application. I'd still like to help, but could I get some pointers as to where changes need to be made (other than updating the min css file in index.html)?

**Comment by coderbyheart** [comment]
Hei a6you, thank you for checking out this project and offering to contribute, which we highly appreciate. 

I haven't looked into it, but I expect that some layouts could be needed to be reworked. 
Also the v5 support is [still pending in reactstrap](https://github.com/reactstrap/reactstrap/issues/1748) so this also needs investigation, whether it makes sense to switch now.

I realize that [according to my own description](https://nordicsemiconductor.github.io/asset-tracker-cloud-docs/saga/CONTRIBUTING.html#finding-open-issues) this issue shouldn't have been labeled with `good first issue`. My apologies for making this look straightforward.

**Comment by a6you** [comment]
I suppose I'll hold off on contributing anything for now, then?

**Comment by coderbyheart** [comment]
We have a smaller app which also needs an update to v5, you could have a look at that: https://github.com/NordicSemiconductor/asset-tracker-cloud-device-ui-js/pull/167

I would be fine to remove reactstrap from that project, because we use only a few elements.

**Comment by a6you** [comment]
Hi, sorry for not replying for so long - other commitments came up. If there's nothing else you'd like me to take look at, then hopefully the project goes well from here!

**Comment by coderbyheart** [comment]
Thanks!

**Comment by coderbyheart** [comment]
reactstrap 9 has now been released which adds support for Bootstrap 5

**Comment by coderbyheart** [comment]
This is solved in https://github.com/NordicSemiconductor/asset-tracker-cloud-app-aws-js
