### ISSUE TITLE
Historical location tooltip shows invalid connection data

### ISSUE THREAD

**Issue by coderbyheart** [NordicSemiconductor/asset-tracker-cloud-app-js#315]
![image](https://user-images.githubusercontent.com/188915/120887279-2f39b280-c5f2-11eb-9bc8-e46bde4768b8.png)

**Comment by FaitAccompli** [comment]
Hi @coderbyheart, 

I'd like to work on this next. The desired output for this is that the Connection, MCC/MNC, Area Code, Cell ID, IP should be populated right?

**Comment by coderbyheart** [comment]
Yes.

**Comment by coderbyheart** [comment]
However, let's hold off on this. It involves interleaving multiple messages from historical data, GNSS and ROAM are reported not in the same update, and we should add this in https://github.com/NordicSemiconductor/asset-tracker-cloud-app-aws-js
