### ISSUE TITLE
Add ability to control time range for charts and map

### ISSUE THREAD

**Issue by coderbyheart** [NordicSemiconductor/asset-tracker-cloud-app-js#82]
It should be possible for the user to select the time range of the charts and the map so they are comparable.
Right now every chart has it's own time range depending on the amount of messages, because most queries use `LIMIT 100`.

![image](https://user-images.githubusercontent.com/188915/108702168-2fadb200-7509-11eb-9e9f-606d5455b4f7.png)

**Comment by FaitAccompli** [comment]
Hi @coderbyheart, 

For this, should we allow users to set a relative time range for all the charts? For each chart or for both? I can work on this. 

By relative time ranges, I mean like a dropdown with 5m ago, a day ago, this week etc.

**Comment by coderbyheart** [comment]
I have started to work in this while looking into #451. In the Golioth Web App there is the [ChartDateRange](https://github.com/coderbyheart/asset-tracker-cloud-app-golioth/blob/5642a08229c1e25e27590a3f509bae5714cdfadd/src/components/ChartDateRange.tsx) component, which handles this.

I am in the progress of implemention the work from `app-golioth` in the new [web-application for AWS repo](https://github.com/NordicSemiconductor/asset-tracker-cloud-app-aws-js).

So I consider this solved.
